Team_Nyala-main/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :transactions
  get 'transactions/index'
  get 'transactions/new'
  get 'transactions/create'

  devise_for :users, :controllers => {
  registrations: 'registrations'
}
  resource :users

  # resource: home
  root 'home#index'
  get 'home/about'
  get 'home/contact'

  match 'my-account', :to => "users#show", :via => :get
end

Team_Nyala-main/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

Team_Nyala-main/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Team_Nyala-main/app/models/currency.rb
class Currency < ApplicationRecord
  has_many :transactions
end

Team_Nyala-main/app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :sender, :class_name => 'User'
  belongs_to :currency, :class_name => 'Currency'
end

Team_Nyala-main/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :transactions
  validates :phone, numericality: {only_integer: true}
  validates :phone, length: {minimum:10}
  validates_format_of :first_name, with: /[-a-z]+/
  validates_format_of :last_name, with: /[-a-z]+/
end

Team_Nyala-main/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Team_Nyala-main/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if(user_signed_in?)
      @balance = '%.2f' % User.find(current_user.id).balance
    else
      @balance = nil
    end
  end

  def about
  end

  def contact
  end
end

Team_Nyala-main/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:user).permit(:email, :password, :password_confirmation, :first_name, :last_name, :date_of_birth, :phone)
    end
end

Team_Nyala-main/app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  TextTransaction = Struct.new(:recipient_name, :currency_string, :time_string)
  def index
    if(!user_signed_in?)
      redirect_to('/401.html')
      return
    end
    @balance = '%.2f' % User.find(current_user.id).balance
    transactions = Transaction.all.where(:sender == User.find(current_user.id))
    if(transactions.length == 0)
      render('no-transactions')
      return
    else
      @transactions = Array.new
      transactions.each do |t|
        transaction = TextTransaction.new
        transaction.currency_string = t.currency.symbol + ('%.2f' % t.amount)
        transaction.recipient_name = t.recipient_name
        transaction.time_string = t.updated_at
        @transactions.push(transaction)
      end
    end
  end

  def show
  end

  def new
    @transaction = Transaction.new
    @currencies = Currency.all
    @balance = '%.2f' % User.find(current_user.id).balance
  end

  def create
    values = transaction_params
    values[:sort_code] = values[:sort_code].tr('-', '')

    @errors = error_messages(values)
    if(@errors.length > 0)
      @transaction = Transaction.new
      @currencies = Currency.all
      @balance = User.find(current_user.id).balance
      render(new_transaction_path)
      return
    else
      user = User.find(current_user.id)
      values[:sender] = user
      values[:currency] = Currency.find(values[:currency])

      @transaction = Transaction.new(values)

      if @transaction.save
        # If save succeeds, redirect to the index action
        user.balance = user.balance - values[:amount].to_d * values[:currency].valueInPounds.to_d
        user.save
        redirect_to(transactions_path)
      else
        # If save fails, redisplay the form so user can fix problems
        render('new')
      end
    end
  end




  private

  def error_messages(transaction_values)
    errors = Array.new
    validate_amount(transaction_values[:amount], errors)
    validate_currency(transaction_values[:currency], errors)
    validate_sender(current_user, errors)
    if(errors.length() == 0)
      validate_sufficient_funds(transaction_values[:amount].to_d, Currency.find(transaction_values[:currency]), errors)
    end
    validate_sort_code(transaction_values[:sort_code], errors)
    validate_name(transaction_values[:recipient_name], errors)
    validate_recipient(transaction_values[:sort_code], transaction_values[:account_number], errors)

    return errors
  end

  def get_recipient(transaction)
    if (transaction.sort_code == "050505")
      return User.find(transaction.account_number)
    else
      return nil
    end
  end

  def validate_recipient(sort_code, account_number, errors)
    if(!valid_nyala_recipient(sort_code, account_number))
      errors.push("That account does not exist.\nPlease check the account number and sort code before sending again.")
    end
  end

  def valid_nyala_recipient(sort_code, account_number)
    if(sort_code != "050505")
      return true
    else
      return User.exists?(account_number)
    end
  end

  def validate_currency(currency, errors)
    if(!Currency.exists? id: currency)
      errors.push("Invalid currency parameter")
    end
  end

  def validate_sender(sender, errors)
    if((sender == nil) || (!User.exists? id: sender.id))
      errors.push("You must be logged in to make a transaction")
    end
  end

  def validate_name(name, errors)
    if(name.blank?)
      errors.push("Name cannot be blank")
    end
  end

  def validate_sort_code(sort_code, errors)
    if(sort_code.length != 6)
      errors.push("Sort code must be 6 digits long")
    end
    if(!sort_code.match(/^(\d|-)*$/))
      errors.push("Sort code must contain only numbers and dashes")
    end
  end

  def validate_amount(amount, errors)
    if(!is_double(amount))
      errors.push("Amount must be a number")
      errors.push("Amount: " + amount)
    elsif(amount.to_d < 0)
      errors.push("Amount must not be negative")
    end
  end

  def validate_sufficient_funds(amount, currency, errors)
    if (!has_sufficient_funds(User.find(current_user.id),amount,currency))
      errors.push("You do not have sufficient funds to make this transaction")
    elsif amount <= 0
        errors.push("Amount must be positive")
    end
  end

  def has_sufficient_funds(user, amount, currency)
    return (user.balance >= amount * currency.valueInPounds)
  end

  def is_integer(string)
    return string.to_i.to_s == string
  end

  def is_double(string)
    return string.match(/^\d+\.\d{0,2}$/)
  end

  def transaction_params
    params.require(:transaction).permit(:sender, :amount, :currency, :recipient_name, :sort_code, :account_number)
  end
end

Team_Nyala-main/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  def show
    #Searches the database for a user
    @user = User.find(current_user.id)
  end

  def edit
    
  end

end

Team_Nyala-main/app/helpers/application_helper.rb
module ApplicationHelper
end

Team_Nyala-main/app/helpers/home_helper.rb
module HomeHelper
end

Team_Nyala-main/app/helpers/nyalausers_helper.rb
module NyalausersHelper
end

Team_Nyala-main/app/helpers/transactions_helper.rb
module TransactionsHelper
end

Team_Nyala-main/app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to 'Bank Nyala', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <%# Creating the links to the pages. %>
            <li class="nav-item">
                <%= link_to "About", home_about_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "Contact", home_contact_path, class:"nav-link"%>
            </li>
            <%# If the User Signed In show those pages below: %>
            <% if user_signed_in?%>
            <li class="nav-item">
                <%= link_to "My Account", "/my-account", class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "Make Transaction", new_transaction_path, method: :get, class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "My Statement", transactions_path, method: :get, class:"nav-link"%>
            </li>
            <%# Else show those pages below: %>
            <% else %>
            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
            </li>
            <%end%>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

Team_Nyala-main/app/views/home/about.html.erb
<div class="container">
  <div class="card" style="width: 100%">
    <div class="card-body">
      <h3 class="card-title" style="color:black">ABOUT NYALA</h3>
      <hr>
      <p class="card-text" style="color: black">Welcome to Nyala, a distinctive bank focussing on moving, lending and protecting money for our customers worldwide.  </p>
    </div>
  </div>
  <br><br>
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://elba-1.org.uk/wp-content/uploads/2018/02/1600px-canary_wharf_skyline_2_london_uk_-_oct_2012.jpg" class="d-block w-100" alt="..." width="1600" height="600">
      <div class="carousel-caption d-none d-md-block">
        <h5>Our Ambition</h5>
        <p>We aim to be the worlds leading bank, helping our clients thrive globally in their financial management</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://bankingblog.accenture.com/wp-content/uploads/2020/09/Banking-Technology-Vision-Innovation-COVID.jpg" class="d-block w-100" alt="..." width="1600" height="600">
      <div class="carousel-caption d-none d-md-block">
        <h5>Our Strategy</h5>
        <p>We maintain a robust capital, investment and liquidity position by operating a diverse business model with minimal earnings volatility </p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://www.canterbury.ac.nz/business/what-can-i-study/international-business/hand-touching-3d-rendering-of-world-and-networks_208128647867203403.jpg" class="d-block w-100" alt="..." width="1600" height="600">
      <div class="carousel-caption d-none d-md-block">
        <h5>Our Values</h5>
        <p>At Nyala, we believe in acting with valiant integrity. We are dependable, strongly connected to our customers and open to different ideas and cultures</p>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
  <br><br>
  <div class="container" style="background-color:white; color:black">
    <br>
  <ul class="list-unstyled">
  <li class="media">
    <img src="https://www.geophysical.com/wp-content/uploads/2017/10/careers-icon-time.svg" class="mr-3" alt="..." width="100" height="100">
    <div class="media-body">
      <h5 class="mt-0 mb-1">Our Team</h5>
      Our highly skilled functional and operational teams serve our customers through an extensive network of offices accross the country.
    <br><br><hr></div>
  </li>
  <li class="media my-4">
    <img src="https://www.clker.com/cliparts/7/a/f/d/14985763421155770474add-client-icon.hi.png" class="mr-3" alt="..." width="100" height="100">
    <div class="media-body">
      <h5 class="mt-0 mb-1">Our Clients</h5>
      Our clients range from individual savers to some of the world's largest organisatioins. We aim to assist each specific client through their financial journeys and accomplish their ambitions.
    <br><br><hr></div>
  </li>
  <li class="media">
    <img src="https://cdn.iconscout.com/icon/premium/png-256-thumb/financial-graph-1464303-1238750.png" class="mr-3" alt="..." width="100" height="100">
    <div class="media-body">
      <h5 class="mt-0 mb-1">Our Impact</h5>
      We've helped our clients move forward by putting them at the heart of everything we do, by connecting the different aspects of their lives to their financial lives. We've made their everyday banking much more convenient through our simple online services.
    </div>
  </li>
</ul>
<br>
</div>
  <br>
  <br>

  </div>
  <br><br>

Team_Nyala-main/app/views/home/contact.html.erb
<div class="container">
<div class="card" style="width: 100%; background-color:white">
  <div class="card-body">
    <h3 class="card-title" style="color:black">CONTACT NYALA</h3>
    <hr>
    <p class="card-text" style="color:black">There are many ways to contact us. Please have a look at the options below, and select the option that best suits you. </p>
  </div>
</div>
<br><br>
  <div class="row">
    <div class="col-sm">
      <div class="card" style="width: 17rem;">
  <img src="https://www.macworld.co.uk/cmsdata/features/3688699/how-to-use-iphone-gestures-main_thumb800.png" class="card-img-top" alt="..." width="500" height="200">
  <div class="card-body">
    <p class="card-text" style="color: black">Contact us by phone by dialing 0800-0000-000. Please note, due to the challenging times we're all facing during the ongoing pandemic, we're dealing with a much greater number of calls as usual. Hence, our call times may be much longer than normal so we ask that you only call if your enquiry is urgent.               <br><br></p>
  </div>
</div>
    </div>
    <div class="col-sm">
      <div class="card" style="width: 18rem;">
  <img src="https://s.wsj.net/public/resources/images/FN-AD982_FN_CWH_M_20180621115904.jpg" class="card-img-top" alt="..." width="500" height="200">
  <div class="card-body">
    <p class="card-text" style="color: black">Most of our branches remain open as of now, but occasionally the opening hours may vary. During your visit, social distancing measures are in place to help keep us all safe. You'll be required to wear a face mask unless you are unable to do so. We're helping our customers as quick as we can, but we may ask you to queue outside if things start to get busy. </p>
  </div>
</div>
    </div>
    <div class="col-sm">
      <div class="card" style="width: 17rem;">
  <img src="https://media.sproutsocial.com/uploads/2017/11/Social-Media-Ideas.png" class="card-img-top" alt="..." width="500" height="200">
  <div class="card-body">
    <p class="card-text" style="color: black">The quickest way to speak to us directly is through our genuine social network accounts with verfified badges. Our team will be available to speak to here 24/7! We'll never ask for your banking passcodes or PINS, please be aware of false accounts imitating us under similar names. <br><br><br></p>
  </div>
</div>
    </div>
  </div>
  <br>
  <br>
  <div class="card" style="width: 100%">
    <div class="accordion" id="accordionExample"><br>
      <h3 class="card-title" style="color:black">Frequently Asked Questions</h3><br>
  <div class="card">
    <div class="card-header" id="headingOne">
      <h3 class="mb-0">
        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne" style="text-decoration:none; color:black">
          How do I check my balance?
        </button>
      </h3>
    </div>

    <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        <p style="color: black">You can check your balance by logging into our online banking site. Here you'll be able to see your balance on an account card you have with us.
        </p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h3 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo" style="text-decoration:none; color:black">
          How do I pay someone new?
        </button>
      </h3>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
        <p style="color: black">Simply log into your online banking account and enter your payees details on the transactions page. You'll then be able to send them an amount upto your total balance.
        </p>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h3 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree" style="text-decoration:none; color:black">
          What if I don't recognise a transaction on my account?
        </button>
      </h3>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body">
        <p style="color: black">We're here to help if you notice a suspicious payment. There's usually a number of common reasons for this such as a company you know may be trading under a different name. It could also be a regular payment or a free trial has ended and charged you. If you still don't recognise it, please contact us ASAP!
        </p>
      </div>
    </div>
  </div>
</div>
      </div>

  </div>
  <br><br>

Team_Nyala-main/app/views/home/index.html.erb
<h1>Bank Nyala UK</h1>
<% if @balance != nil %>
  <h1 class="balance">Account balance: £<%= @balance %></h1>
<% end %>
<h2><b>We are the best at what we do!<b></h2>

Team_Nyala-main/app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

Team_Nyala-main/app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Bank Nyala</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'home/header' %>
    <div class="container">
        <br />
        <% if notice  %>
        <%= render 'layouts/alerts'%>
        <% end %>

        <%= yield %>
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
</body>

</html>

Team_Nyala-main/app/views/transactions/index.html.erb
<h3 class="title">Your Statement</h3>
<h3 class="balance"> Account balance: £<%= @balance %> </h3>
<% @transactions.each do |t| %>
  <div class="transaction-panel">
    <%= t.recipient_name %><br/>
    <%= t.currency_string %><br/>
    <%= t.time_string %>
  </div>
  <br/>
<% end %>

Team_Nyala-main/app/views/transactions/new.html.erb
<div class="transaction new">
  <h2>Send Money</h2>

  <h4 class="balance">Account balance: £<%= @balance %></h4>

  <% @errors != nil && if(@errors.length > 0) %>
    <div class="errors">
    <% @errors.each do |e| %>
      <p class="error">
        <%= e %>
      <p/>
    <% end %>
    </div>
  <% end %>

  <%= form_for(@transaction, :url => transactions_path, :method => 'post') do |f| %>

  <div class="field">
      <%= f.label :recipient_name%><br/>
      <%= f.text_field :recipient_name, autocomplete: "Recipient Name" %>
  </div>

  <div class="field">
      <%= f.label :sort_code%><br/>
      <%= f.text_field :sort_code, autocomplete: "Sort Code" %>
  </div>

  <div class="field">
      <%= f.label :account_number%><br/>
      <%= f.text_field :account_number, autocomplete: "Account Number" %>
  </div>

  <div class="field">
      <%= f.label :amount%><br/>
      <%= f.number_field :amount, value: number_to_currency(f.object.amount.to_f, delimiter: '', unit: ''), min:0, step: 0.01 %>
  </div>

  <div class="field">
      <%= f.label :currency%><br/>
      <%= f.select :currency, @currencies.map{ |c| [c.isoCode, c.id] } %>
  </div>

  <br/>
  <div class="actions">
      <%= f.submit "Make Transaction" %>
  </div>

  <% end %>
</div>

Team_Nyala-main/app/views/transactions/no-transactions.html.erb
<h1>Transactions#index</h1>
<p>Find me in app/views/transactions/index.html.erb</p>

Team_Nyala-main/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
<% if user.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
        <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name%>
</div>

<div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
</div>

<div class="field">
    <%= form.label :date_of_birth %>
    <%= form.text_field :date_of_birth %>
</div>

<div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
</div>

<div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>

Team_Nyala-main/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'show', @user %> |

Team_Nyala-main/app/views/users/index.html.erb
<h1>My Account</h1>

<table>
    <thead>
        <tr>
            <th>First name</th>
            <th>Last name</th>
            <th>Date of Birth</th>
            <th>Email</th>
            <th>Phone</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @users.each do |user| %>
        <tr>
            <td><%= user.first_name %></td>
            <td><%= user.last_name %></td>
            <td><%= user.date_of_birth %></td>
            <td><%= user.email %></td>
            <td><%= user.phone %></td>
            <%# <%= link_to 'Show', user %>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>
<%if @users.size() == 0 %>
<%= link_to 'Update my account', new_user_path %>
<%end%>

Team_Nyala-main/app/views/users/show.html.erb
<p>
    <strong>First name:</strong>
    <%= @user.first_name %>
</p>

<p>
    <strong>Last name:</strong>
    <%= @user.last_name %>
</p>

<p>
    <strong>Date of birth:</strong>
    <%= @user.date_of_birth %>
</p>

<p>
    <strong>Email:</strong>
    <%= @user.email %>
</p>

<p>
    <strong>Phone:</strong>
    <%= @user.phone %>
</p>

<%= link_to 'Edit', 'edit' %> |
<%= link_to 'Back', users_path %>